"""empty message

Revision ID: 1956c77d7bdd
Revises: 5f5074229701
Create Date: 2021-09-12 10:21:26.231726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1956c77d7bdd'
down_revision = '5f5074229701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Round', sa.Column('ext_round_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Round', 'ext_round_id')
    # ### end Alembic commands ###
