"""empty message

Revision ID: 1c484f3ca20e
Revises: 80c60bbccf1a
Create Date: 2021-09-15 20:37:59.220591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c484f3ca20e'
down_revision = '80c60bbccf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Transaction_ibfk_5', 'Transaction', type_='foreignkey')
    op.drop_column('Transaction', 'round_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('round_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Transaction_ibfk_5', 'Transaction', 'Round', ['round_id'], ['round_id'])
    # ### end Alembic commands ###
