"""empty message

Revision ID: 37568464e7ea
Revises: ff7a7c8a463e
Create Date: 2021-09-15 19:47:39.400750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37568464e7ea'
down_revision = 'ff7a7c8a463e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Round', sa.Column('stake', sa.Integer(), nullable=False))
    op.add_column('Round', sa.Column('win', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Round', 'win')
    op.drop_column('Round', 'stake')
    # ### end Alembic commands ###
