"""empty message

Revision ID: 90189fdc2614
Revises: 92db8b02f725
Create Date: 2021-09-16 18:09:02.102689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90189fdc2614'
down_revision = '92db8b02f725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Transaction_ibfk_5', 'Transaction', type_='foreignkey')
    op.create_foreign_key(None, 'Transaction', 'Round', ['round_id'], ['round_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transaction', type_='foreignkey')
    op.create_foreign_key('Transaction_ibfk_5', 'Transaction', 'Round', ['round_id'], ['round_id'])
    # ### end Alembic commands ###
