"""empty message

Revision ID: 92db8b02f725
Revises: 1c484f3ca20e
Create Date: 2021-09-15 20:39:26.847058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92db8b02f725'
down_revision = '1c484f3ca20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('round_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Transaction', 'Round', ['round_id'], ['round_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transaction', type_='foreignkey')
    op.drop_column('Transaction', 'round_id')
    # ### end Alembic commands ###
