"""empty message

Revision ID: be4ae7bc2b0a
Revises: 37568464e7ea
Create Date: 2021-09-15 20:16:53.467121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be4ae7bc2b0a'
down_revision = '37568464e7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Transaction_ibfk_1', 'Transaction', type_='foreignkey')
    op.drop_column('Transaction', 'round_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('round_id', mysql.VARCHAR(length=50), nullable=True))
    op.create_foreign_key('Transaction_ibfk_1', 'Transaction', 'Round', ['round_id'], ['round_id'])
    # ### end Alembic commands ###
