"""empty message

Revision ID: c8378de8fba5
Revises: be4ae7bc2b0a
Create Date: 2021-09-15 20:17:42.342334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8378de8fba5'
down_revision = 'be4ae7bc2b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('round_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Transaction', 'Round', ['round_id'], ['round_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transaction', type_='foreignkey')
    op.drop_column('Transaction', 'round_id')
    # ### end Alembic commands ###
