"""empty message

Revision ID: ff7a7c8a463e
Revises: 1956c77d7bdd
Create Date: 2021-09-12 13:14:38.986831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7a7c8a463e'
down_revision = '1956c77d7bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Session', sa.Column('validated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Session', 'validated')
    # ### end Alembic commands ###
